export const ADD_SUBTASK = 'ADD_SUBTASK';
export const UPD_SUBTASK = 'UPD_SUBTASK';
export const DEL_SUBTASK = 'DEL_SUBTASK';
export const INIT_FROM_JIRA_ITEM = 'INIT_FROM_JIRA_ITEM';
export const UPD_ROOT_ITEM_KEY = 'UPD_ROOT_ITEM_KEY';
export const UPD_FOCUS_FACTOR = 'UPD_FOCUS_FACTOR';

export const FETCH_JIRA_ITEM_PENDING = 'FETCH_JIRA_ITEM_PENDING';
export const FETCH_JIRA_ITEM_SUCCESS = 'FETCH_JIRA_ITEM_SUCCESS';
export const FETCH_JIRA_ITEM_FAIL = 'FETCH_JIRA_ITEM_FAIL';

export const CREATE_SUBTASK_PENDING = 'CREATE_SUBTASK_PENDING';
export const CREATE_SUBTASK_SUCCESS = 'CREATE_SUBTASK_SUCCESS';
export const CREATE_SUBTASK_FAIL = 'CREATE_SUBTASK_FAIL';

export const UPD_SUBTASK_PENDING = 'UPD_SUBTASK_PENDING';
export const UPD_SUBTASK_SUCCESS = 'UPD_SUBTASK_SUCCESS';
export const UPD_SUBTASK_FAIL = 'UPD_SUBTASK_FAIL';

export const FETCH_STATUSES_PENDING = 'FETCH_STATUSES_PENDING';
export const FETCH_STATUSES_SUCCESS = 'FETCH_STATUSES_SUCCESS';
export const FETCH_STATUSES_FAIL = 'FETCH_STATUSES_FAIL';

export const FETCH_SUBTASKS_PENDING = 'FETCH_SUBTASKS_PENDING';
export const FETCH_SUBTASKS_SUCCESS = 'FETCH_SUBTASKS_SUCCESS';
export const FETCH_SUBTASKS_FAIL = 'FETCH_SUBTASKS_FAIL';

export const CLEAR_ERROR = 'CLEAR_ERROR';

export const DISCARD_ALL = 'DISCARD_ALL';

export const UPD_LABEL_FILTER = 'UPD_LABEL_FILTER';
export const CLEAR_LABEL_FILTER = 'CLEAR_LABEL_FILTER';

