export const INC_FOO = 'INC_FOO';
export const DEC_FOO = 'DEC_FOO';
export const ADD_SUBTASK = 'ADD_SUBTASK';
export const UPD_SUBTASK = 'UPD_SUBTASK';
export const DEL_SUBTASK = 'DEL_SUBTASK';
export const INIT_FROM_JIRA_ITEM = 'INIT_FROM_JIRA_ITEM';
export const UPD_ROOT_ITEM_KEY = 'UPD_ROOT_ITEM_KEY';
export const UPD_FOCUS_FACTOR = 'UPD_FOCUS_FACTOR';

export const FETCH_JIRA_ITEM_PENDING = 'FETCH_JIRA_ITEM_PENDING';
export const FETCH_JIRA_ITEM_SUCCESS = 'FETCH_JIRA_ITEM_SUCCESS';
export const FETCH_JIRA_ITEM_FAIL = 'FETCH_JIRA_ITEM_FAIL';

export const CREATE_SUBTASK_PENDING = 'CREATE_SUBTASK_PENDING';
export const CREATE_SUBTASK_SUCCESS = 'CREATE_SUBTASK_SUCCESS';
export const CREATE_SUBTASK_FAIL = 'CREATE_SUBTASK_FAIL';

export const UPD_SUBTASK_PENDING = 'UPD_SUBTASK_PENDING';
export const UPD_SUBTASK_SUCCESS = 'UPD_SUBTASK_SUCCESS';
export const UPD_SUBTASK_FAIL = 'UPD_SUBTASK_FAIL';

export const UPD_USER = 'UPD_USER';
export const UPD_PASS = 'UPD_PASS';

export const CLEAR_ERROR = 'CLEAR_ERROR';

